/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "steamingmind.com/apiserver-demo/pkg/apis/demo/v1alpha1"
)

// FakeFooBars implements FooBarInterface
type FakeFooBars struct {
	Fake *FakeDemoV1alpha1
	ns   string
}

var foobarsResource = schema.GroupVersionResource{Group: "demo.streamingmind.com", Version: "v1alpha1", Resource: "foobars"}

var foobarsKind = schema.GroupVersionKind{Group: "demo.streamingmind.com", Version: "v1alpha1", Kind: "FooBar"}

// Get takes name of the fooBar, and returns the corresponding fooBar object, and an error if there is any.
func (c *FakeFooBars) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FooBar, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(foobarsResource, c.ns, name), &v1alpha1.FooBar{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FooBar), err
}

// List takes label and field selectors, and returns the list of FooBars that match those selectors.
func (c *FakeFooBars) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FooBarList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(foobarsResource, foobarsKind, c.ns, opts), &v1alpha1.FooBarList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FooBarList{ListMeta: obj.(*v1alpha1.FooBarList).ListMeta}
	for _, item := range obj.(*v1alpha1.FooBarList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fooBars.
func (c *FakeFooBars) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(foobarsResource, c.ns, opts))

}

// Create takes the representation of a fooBar and creates it.  Returns the server's representation of the fooBar, and an error, if there is any.
func (c *FakeFooBars) Create(ctx context.Context, fooBar *v1alpha1.FooBar, opts v1.CreateOptions) (result *v1alpha1.FooBar, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(foobarsResource, c.ns, fooBar), &v1alpha1.FooBar{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FooBar), err
}

// Update takes the representation of a fooBar and updates it. Returns the server's representation of the fooBar, and an error, if there is any.
func (c *FakeFooBars) Update(ctx context.Context, fooBar *v1alpha1.FooBar, opts v1.UpdateOptions) (result *v1alpha1.FooBar, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(foobarsResource, c.ns, fooBar), &v1alpha1.FooBar{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FooBar), err
}

// Delete takes name of the fooBar and deletes it. Returns an error if one occurs.
func (c *FakeFooBars) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(foobarsResource, c.ns, name), &v1alpha1.FooBar{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFooBars) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(foobarsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.FooBarList{})
	return err
}

// Patch applies the patch and returns the patched fooBar.
func (c *FakeFooBars) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FooBar, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(foobarsResource, c.ns, name, pt, data, subresources...), &v1alpha1.FooBar{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FooBar), err
}
